/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

import Esencial.Imagen;
import Esencial.Usuario;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Usuario
 */
public class Identificacionnnn extends javax.swing.JPanel {
    Usuario usuario;

    /**
     * Creates new form FichaUsuario
     */
    public Identificacionnnn(Usuario usuario,int rank) {
        this.usuario = usuario;
        
        initComponents();
        generarCodigoDeBarras();
        llenarFicha();
    }
    
    
    public void llenarFicha(){
        lblNombre.setText("Nombre: "+ usuario.getNombre());
        lblApellido.setText("Apellido: "+ usuario.getApellido());
        lblCedula.setText("Cedula: "+ usuario.getCedula());
        lblCargo.setText("Cargo: "+ usuario.getCargo() );
        panelImagen.add(new Fondo(150,150,new ImageIcon(Imagen.decodeToImage(usuario.getImagen()))));
    }
    
    public void generarCodigoDeBarras(){
        
        //final BarCodeRenderer barCodeRenderer = new UPCABarCodeRenderer();
        
        JPanel panel = new JPanel() {
                                        @Override
                                        public void paint(Graphics g) {
                                            Dimension size = getSize();
                                            g.setColor(getBackground());
                                            g.fillRect(0, 0, size.width, size.height);
                                            g.setColor(getForeground());
                                            g.translate(10, 10);
          //                                  barCodeRenderer.render(g, usuario.getCedula(), 1, 80, 12);
                        }
                                    };
        
        jpnFondoCodigoBarra.add(panel);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImagen = new javax.swing.JPanel();
        lblNombre = new javax.swing.JLabel();
        lblApellido = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        lblCargo = new javax.swing.JLabel();
        jpnFondoCodigoBarra = new javax.swing.JPanel();

        setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout panelImagenLayout = new javax.swing.GroupLayout(panelImagen);
        panelImagen.setLayout(panelImagenLayout);
        panelImagenLayout.setHorizontalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        panelImagenLayout.setVerticalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        lblNombre.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        lblNombre.setText("Nombre:");

        lblApellido.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N
        lblApellido.setText("Apellido:");

        lblCedula.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N
        lblCedula.setText("Cédula:");

        lblCargo.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N
        lblCargo.setText("Cargo:");

        jpnFondoCodigoBarra.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jpnFondoCodigoBarraLayout = new javax.swing.GroupLayout(jpnFondoCodigoBarra);
        jpnFondoCodigoBarra.setLayout(jpnFondoCodigoBarraLayout);
        jpnFondoCodigoBarraLayout.setHorizontalGroup(
            jpnFondoCodigoBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
        );
        jpnFondoCodigoBarraLayout.setVerticalGroup(
            jpnFondoCodigoBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCargo)
                            .addComponent(lblNombre)
                            .addComponent(lblCedula)
                            .addComponent(lblApellido)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpnFondoCodigoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addGap(18, 18, 18)
                        .addComponent(lblApellido)
                        .addGap(18, 18, 18)
                        .addComponent(lblCedula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCargo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnFondoCodigoBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpnFondoCodigoBarra;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JPanel panelImagen;
    // End of variables declaration//GEN-END:variables
}
